exports.data = {
	goods : [ {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "001",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "002",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "003",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "004",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "005",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "006",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "007",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "008",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "009",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	}, {
		"currPrice" : "<currPrice>",
		"desc" : "<desc>",
		"goodsId" : "010",
		"isNew" : "<isNew>",
		"name" : "<name>",
		"onSale" : "<onSale>",
		"photo" : "<photo>",
		"price" : "<price>",
		"registerTime" : "<registerTime>",
		"stock" : "<stock>",
		"categoryId" : "<categoryId>"
	} ]
};
